# Generated by Django 5.0.6 on 2024-06-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_user_note_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner',
            new_name='user',
        ),
    ]
