# Generated by Django 5.0.6 on 2024-06-05 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_collaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborative_notes', through='website.Collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
