import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Dialog } from "@/Components/ui/dialog";

import { cn } from "@/lib/utils";
import { Button } from "@/Components/ui/button";
import { ModeToggle } from "@/Components/ui/mode-toggle";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex justify-between items-center border-b-4  p-2">
            <h1><Dialog/></h1>
            <ModeToggle />
          </header>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Searchbar } from "@/Components/Searchbar";
// import Sidebar from "@/Components/Sidebar";
// import LoginForm from "@/Components/LoginForm";
// import Link from "next/link";
// import Login from "./login/page";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="container flex">
//           <div className="_Sidebar flex flex-col h-screen w-60 bg-slate-600 p-2">
//             {/* <Sidebar /> */}
//             <Link href="/" className="text-slate-50">
//               Logo
//             </Link>
//             <Link href="/login" className="text-slate-50">
//               Login
//             </Link>
//           </div>

//           <div className="main flex flex-col">
//             <header className="p-2">

//             </header>
//             <div>{children}</div>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
